language: bash

notifications:
  email: false

services:
  - docker

script:
  - source tango.properties
  - docker build --build-arg TANGO_DISTRIBUTION_VERSION=${TANGO_DISTRIBUTION_VERSION} -t tangocs/tango-libs .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag tangocs/tango-libs tangocs/tango-libs:${TANGO_DISTRIBUTION_VERSION}

deploy:
  - provider: script
    script: docker push tangocs/tango-libs:latest
    on:
      all_branches: true
  - provider: script
    script: docker push tangocs/tango-libs:${TANGO_DISTRIBUTION_VERSION}
    on:
      all_branches: true
